name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd module_4
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            sleep 2
          done

      - name: Initialize DB schema
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/testdb
        run: |
          psql $DATABASE_URL -c "
          CREATE TABLE IF NOT EXISTS applicants (
              p_id SERIAL PRIMARY KEY,
              program TEXT,
              comments TEXT,
              date_added DATE,
              url TEXT UNIQUE,
              status TEXT,
              term TEXT,
              us_or_international TEXT,
              gpa FLOAT,
              gre FLOAT,
              gre_v FLOAT,
              gre_aw FLOAT,
              degree TEXT,
              llm_generated_program TEXT,
              llm_generated_university TEXT
          );"

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/testdb
        run: |
          cd module_4
          pytest -m "web or buttons or analysis or db or integration" -v --maxfail=1 --disable-warnings

